version: 2
before:
  hooks:
  - go mod download
builds:
- id: manager
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd/manager/main.go
  binary: manager
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  flags:
  - -a
  ldflags:
  - -s -w -X github.com/pfnet/hierarchical-namespaces/cmd.Version={{.Version}} -X github.com/pfnet/hierarchical-namespaces/cmd.Revision={{.ShortCommit}} -extldflags "-static"
- id: api-extension
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd/apiextension/main.go
  binary: apiextension
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  flags:
  - -a
  ldflags:
  - -s -w -X github.com/pfnet/hierarchical-namespaces/cmd.Version={{.Version}} -X github.com/pfnet/hierarchical-namespaces/cmd.Revision={{.ShortCommit}} -extldflags "-static"

dockers:
- image_templates: ["ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile.release
  goarch: amd64
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/pfnet/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/pfnet/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates: ["ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  dockerfile: Dockerfile.release
  goarch: arm64
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/pfnet/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/pfnet/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
- name_template: ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/pfnet/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/pfnet/{{ .ProjectName }}:{{ .Version }}-arm64v8
