name: E2E

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']

env:
  KUBEBUILDER_CONTROLPLANE_STOP_TIMEOUT: 120s

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: make test-e2e
      run: make test-e2e
